-- Active: 1754424561850@@127.0.0.1@3306

CREATE TABLE IF NOT EXISTS Pessoa(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_referencial VARCHAR(260) NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE,
    location_hash VARCHAR(120) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    email_principal VARCHAR(100) NOT NULL UNIQUE,
    tipo CHAR(5) NOT NULL DEFAULT "PF",
    created_at VARCHAR(50) NOT NULL DEFAULT (DATETIME('NOW')),
    updated_at VARCHAR(50) NOT NULL DEFAULT (DATETIME('NOW'))
);


CREATE TABLE IF NOT EXISTS Account (
    master_key VARCHAR(120) PRIMARY KEY UNIQUE NOT NULL,
    account_type CHAR(10) NOT NULL DEFAULT "USER",
    pessoa_idPessoa INT NOT NULL,
    _id VARCHAR(120) DEFAULT NULL,
    created_at VARCHAR(50) NOT NULL DEFAULT (DATETIME('NOW')),
    updated_at VARCHAR(50) NOT NULL DEFAULT (DATETIME('NOW')),
    FOREIGN KEY (pessoa_idPessoa) REFERENCES Pessoa(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

